config/routes.rb
RestaurantRails::Application.routes.draw do
get '/cuisines/:id' => 'cuisines#show', as: 'cuisine'
get '/cuisines' => 'cuisines#index', as: 'cuisines'

get '/pages/' => 'pages#index', as: 'home'
post '/pages/' => 'pages#search', as: 'search'

get '/restaurants' => 'restaurants#index', as: 'restaurants'
post 'restaurants' => 'restaurants#index'
get "/restaurants/add_restaurant/:id" => 'restaurants#add_restaurant', as: 'add_restaurant'
get "/restaurants/remove_restaurant/:id" => 'restaurants#remove_restaurant', as: 'remove_restaurant'
get '/restaurants/:id' => 'restaurants#show', as: 'restaurant'

get '/users/:id/remove_restaurant_from_profile' => 'users#remove_restaurant_from_profile', as: 'remove_restaurant_from_profile'
get '/users/:id/remove_violation_from_profile' => 'users#remove_violation_from_profile', as: 'remove_violation_from_profile'

get '/violations/:id' => 'violations#show', as: 'violation'
get '/violations' => 'violations#index', as: 'violations'
get "/violations/add_violation/:id" => 'violations#add_violation', as: 'add_violation'
get '/violations/remove_violation/:id' => 'violations#remove_violation', as: 'remove_violation'

get '/zipcodes/:id' => 'zipcodes#show', as: 'zip'
get '/zipcodes' => 'zipcodes#index'
get "/zipcodes/add_zipcode/:id" => 'zipcodes#add_zipcode', as: 'add_zipcode_show'
get '/zipcodes/remove_zipcode/:id' => 'zipcodes#remove_zipcode', as: 'remove_zipcode_show'


delete '/sessions' => 'sessions#destroy'
get '/sessions/new' => 'sessions#new', as: 'new_session'
post '/sessions' => 'sessions#create'
get 'auth/:provider/callback' => 'sessions#create'
get 'auth/failure' => redirect('/')
get 'signout' => 'sessions#destroy', as: 'signout'

get "/users" => 'users#new'
get "/users/new" => 'users#new', as: "new_user"
post "/users" => 'users#create'

get "/users/:id/edit" => 'users#edit', as: "edit_user"
patch "/users/:id" => 'users#update'

get "/users/:id" => 'users#show', as: "user"
get "/users/remove_zip/:id" => 'users#remove_zip', as: "remove_zip"
delete "/users/:id" => 'users#destroy', as: "destroy_user"

root 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_zipcodes
  has_many :zipcodes, through: :user_zipcodes

  has_many :user_restaurants
  has_many :restaurants, through: :user_restaurants

  has_many :user_cuisines
  has_many :cuisines, through: :user_cuisines

  has_many :user_violations
  has_many :violations, through: :user_violations

  validates_presence_of :name, :email

  has_secure_password
  
  attr_reader :zipcode_list, :cuisine_list

  def zipcodes_as_a_string
    result = ""
    self.zipcodes.each { |z| result = result + z.zip.to_s + ", " }
    result = result[0,result.length-2] if result.length > 0
    result
  end

  def zipcode_list=(params)
    params.gsub(" ", "").split(",").each do |zip|
      if Zipcode.find_by(zip: zip) && !self.zipcodes.include?(Zipcode.find_by(zip: zip))
        self.zipcodes << Zipcode.find_by(zip: zip)  
      end
    end
  end

  def cuisine_list=(params)
    params.each do |cuisine_id|
      if Cuisine.find_by(id: cuisine_id) && !self.cuisines.include?(id: cuisine_id)
        self.cuisines << Cuisine.find_by(id: cuisine_id)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, :only => [:show, :edit, :update, :destroy]
  before_action :set_user, :only => [:show, :edit, :update, :destroy]
  
  def new
    redirect_if_wrong_profile if signed_in?
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "Your form filling-in skills are lacking.  Try again!"
      render 'new'
    end
  end

  def edit
    redirect_if_wrong_profile
  end

  def update
    @user.update(user_params)
    if @user.save
      flash[:notice] = "User successfully edited"
      redirect_to @user
    else
      flash[:notice] = "Something went wrong.  Try again."
      render 'edit'
    end
  end

  def show
    redirect_if_wrong_profile
  end

  def destroy
    current_user.destroy
    redirect_to '/signout'
  end

  def remove_violation_from_profile
    current_user.user_violations.find_by(violation_id: params[:id]).destroy 
  end

  def remove_restaurant_from_profile
    current_user.user_restaurants.find_by(restaurant_id: params[:id]).destroy 
  end

  def remove_zip
    current_user.user_zipcodes.find_by(zipcode_id: Zipcode.find_by(zip: params[:id]).id)
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :facebook_id, :location, :image_url, :zipcode_list, :restaurant_list, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def is_correct_user?
    current_user ? current_user.id == params[:id].to_i : false
  end

  def redirect_if_wrong_profile
    if !is_correct_user?
      if signed_in?
        redirect_to current_user
      else
        redirect_to new_session_path
      end
    end    
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if flash[:notice] %>
  <div data-alert class="alert-box success radius" style="display:block">
    <%= flash[:notice] %>
  </div>
  <% flash.delete(:notice) %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, value: @user.name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email, value: @user.email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password, value: @user.password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, value: @user.password_confirmation %>
  <br>    
  <label for="zipcode_list">Add your favorite zipcode(s), separated by commas.</label>
  <%= f.text_field :zipcode_list, value: @user.zipcodes_as_a_string %>
  <br>
  <%= f.hidden_field :location, value: @user.location %>
  <%= f.hidden_field :image_url, value: @user.image_url %>
  <%= f.hidden_field :facebook_id, value: @user.facebook_id %>
  <button class="button">Submit</button>
<% end %>

app/views/users/edit.html.erb
<div class="medium-7 columns">
  <%= render 'errors' %>
  <h1>Hey, <%= @user.name %>.</h1>
  <h2>Edit your profile here.</h2>
  <%= render 'form' %>
  <%= link_to "Back to my profile", @user, :class => "button" %>
  <%= link_to "Delete my account", destroy_user_path(@user), :class => "button alert", method: 'delete' %>
</div>

app/views/users/new.html.erb
<div class="medium-7 columns">
  <%= render 'errors' %>
  <h1>Sign up!</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="medium-12 columns">
  <%= render 'errors' %>
  <div class="small-4 columns small-centered">
    <h2 class="centered"><%= @user.name %></h2>
    <h4 class="centered"><%= @user.email %></h4>
  </div>
</div>
<div class="row">
  <h3>Zipcode Watchlist</h3>
  <% if @user.zipcodes.length == 0 %>
    <p class="empty">Empty</p>
  <% else %>
      <% @user.zipcodes.each do |zip| %>
        <div class="whole row ">
            <%= link_to zip.zip, zip_path(zip), 'data-no-turbolink' => true, :class => "large-4 columns" %>
            <%= link_to "✖", remove_zip_path(zip), remote: true, :class => "tiny alert round large-8 columns", :method => :get %>
        </div>
<!--         <br> -->
      <% end %>
  <% end %>
</div>

<div class="row">
  <h3>Violation Watchlist</h3>
  <% if @user.violations.length == 0 %>
   <p class="empty">Empty</p>
  <% else %>
    <% @user.violations.each do |violation| %>
    <div class="whole row">
      <%= link_to violation.short_desc, violation_path(violation), 'data-no-turbolink' => true, :class => "large-4 columns" %>
      <%= link_to "✖", remove_violation_from_profile_path(violation.id), remote: true, :class => "tiny alert round large-8 columns", :method => :get %>
    </div>
    <br>
      <% end %>
  <% end %>
</div>
<div class="row">
  <h3>Restaurant Watchlist</h3>
  <% if @user.restaurants.length == 0 %>
   <p class="empty">Empty</p>
  <% else %>
    <% @user.restaurants.each do |restaurant| %>
    <div class="whole row">
      <%= link_to restaurant.name, restaurant_path(restaurant), 'data-no-turbolink' => true , :class => "large-4 columns" %>
      <%= link_to "✖", remove_restaurant_from_profile_path(restaurant.id), remote: true, :class => "tiny alert round large-8 columns", :method => :get %>
    </div>
    <br>
    <% end %>
  <% end %>
</div>
<br>
  <p class="row centered">

    <%= link_to "Go to Homepage", root_path, :class => "button user_show" %>
    <%= link_to "Edit My Profile", edit_user_path(@user), :class => "button user_show" %>  
    <%= link_to "Log out", signout_path, :class => "button alert" %>
  </p>
</div>