config/routes.rb
RestaurantRails::Application.routes.draw do
get '/cuisines/:id' => 'cuisines#show', as: 'cuisine'
get '/cuisines' => 'cuisines#index', as: 'cuisines'

get '/pages/' => 'pages#index', as: 'home'
post '/pages/' => 'pages#search', as: 'search'

get '/restaurants' => 'restaurants#index', as: 'restaurants'
post 'restaurants' => 'restaurants#index'
get "/restaurants/add_restaurant/:id" => 'restaurants#add_restaurant', as: 'add_restaurant'
get "/restaurants/remove_restaurant/:id" => 'restaurants#remove_restaurant', as: 'remove_restaurant'
get '/restaurants/:id' => 'restaurants#show', as: 'restaurant'

get '/users/:id/remove_restaurant_from_profile' => 'users#remove_restaurant_from_profile', as: 'remove_restaurant_from_profile'
get '/users/:id/remove_violation_from_profile' => 'users#remove_violation_from_profile', as: 'remove_violation_from_profile'

get '/violations/:id' => 'violations#show', as: 'violation'
get '/violations' => 'violations#index', as: 'violations'
get "/violations/add_violation/:id" => 'violations#add_violation', as: 'add_violation'
get '/violations/remove_violation/:id' => 'violations#remove_violation', as: 'remove_violation'

get '/zipcodes/:id' => 'zipcodes#show', as: 'zip'
get '/zipcodes' => 'zipcodes#index'
get "/zipcodes/add_zipcode/:id" => 'zipcodes#add_zipcode', as: 'add_zipcode_show'
get '/zipcodes/remove_zipcode/:id' => 'zipcodes#remove_zipcode', as: 'remove_zipcode_show'


delete '/sessions' => 'sessions#destroy'
get '/sessions/new' => 'sessions#new', as: 'new_session'
post '/sessions' => 'sessions#create'
get 'auth/:provider/callback' => 'sessions#create'
get 'auth/failure' => redirect('/')
get 'signout' => 'sessions#destroy', as: 'signout'

get "/users" => 'users#new'
get "/users/new" => 'users#new', as: "new_user"
post "/users" => 'users#create'

get "/users/:id/edit" => 'users#edit', as: "edit_user"
patch "/users/:id" => 'users#update'

get "/users/:id" => 'users#show', as: "user"
get "/users/remove_zip/:id" => 'users#remove_zip', as: "remove_zip"
delete "/users/:id" => 'users#destroy', as: "destroy_user"

root 'pages#index'

end

app/models/violation.rb
class Violation < ActiveRecord::Base
  has_many :restaurant_violations
  has_many :restaurants, through: :restaurant_violations

  has_many :user_violations
  has_many :users, through: :user_violations

  def critical?
    self.critical_vio
  end

  def self.most_common
    self.joins(:restaurants).group("violations.id").order("count(restaurant_violations.violation_id) desc").limit(3)
  end

  def short_desc
    "#{self.description.slice(0..60)}..."
  end
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController
  before_action :set_violation, only: [:show]
  before_action :set_user, only: [:add_violation, :remove_violation]

  def show
  end

  def index
    @violations = Violation.all
    @search = Violation.search(params[:q])
    @found_violations = @search.result
  end

  def add_violation
    @user = current_user
    v = Violation.find(params[:id])
    @user.violations << v
  end

  def remove_violation
    @user = current_user
    @user.user_violations.find_by(violation_id: params[:id]).destroy
  end

  private
  
  def set_violation
    @violation = Violation.find(params[:id]) 
  end

  def set_user
    @user = current_user
  end
  
end

app/views/violations/add_violation.js.erb
$(".add_vio_watchlist").hide();
$(".remove_vio_watchlist").css( "display", "block").show();

$(".add_violation").fadeIn(900, function(){
  $(".add_violation").fadeOut(300)
});

app/views/violations/index.html.erb
<div class="small-12 columns row search_form">
  <h3 class="centered">Violation Index</h3>
  <%= search_form_for @search do |f| %>
    <%#= f.label :description_cont, "Description Contains:" %>
    <div class="small-8 columns">
      <%= f.text_field :description_cont, placeholder: "Keyword in description..." %>
    </div>
    <div class="small-4 columns">
      <%= f.submit 'Search', :class => "button" %>
    </div>
    <!-- <button class="button small-2 columns">Search Violations</button> -->
  <% end %>
</div>
<div class="row">
</div>

<div class="small-12 columns">
  <div class="small-12 columns">
    <% if params[:q] %>
    <div class="search">
      <% if @found_violations == [] %>
        <%= "Search returned 0 results" %>
      <% else %>
      <h2>Search Results</h2>
        <ol>
        <% @found_violations.each do |v| %>
          <li><%= link_to "#{v.vio_code}. #{v.description}", violation_path(v) %></li>
        <% end %>
        </ol>
      <% end %>

    <% end %>
    </div>



    <table>
      <tr>
        <th>Code</th>
        <th>Description</th>
      </tr>
    <% @violations.each do |v| %>
      <tr>
        <td><%= link_to v.vio_code, violation_path(v) %></td>
        <td><%= v.description %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/violations/remove_violation.js.erb
$(".remove_vio_watchlist").hide();
$(".add_vio_watchlist").css( "display", "block").show();

$(".remove_violation").fadeIn(900, function(){
  $(".remove_violation").fadeOut(300)
});

app/views/violations/show.html.erb
<div class="medium-12 columns">
  <h2 class="centered">Violation <%= @violation.vio_code %></h2>
  <h3 class="centered"><%= @violation.description %></h3>
  <% if @violation.critical_vio == true %>
    <h3 class="red centered">This violation is critical</h3>
  <% end %>
  <br>
  <div class="row">
    <% if current_user == nil || !current_user.violations.include?(@violation) %>
      <div class="small-4 columns small-offset-2">
        <%= link_to "Add to Watchlist", add_violation_path(@violation.id), remote: true, class: "button add_vio_watchlist", data: {user: signed_in?}, style: "display: block" %>
      </div>
      <div class="small-4 columns small-offset-2">
          <%= link_to "Remove from Watchlist", remove_violation_path(@violation.id), remote: true, class: "button remove_vio_watchlist no_display alert" %>
      </div>
    <% else %>
      <div class="small-4 columns small-offset-2">
        <%= link_to "Add to Watchlist", add_violation_path(@violation.id), remote: true, class: "button add_vio_watchlist no_display"%>
      </div>
      <div class="small-4 columns small-offset-2">
          <%= link_to "Remove from Watchlist", remove_violation_path(@violation.id), remote: true, class: "button remove_vio_watchlist alert", style: "display: block" %>
      </div>
    <% end %>
    <div class="small-3 columns">
      <%= link_to "Violation Index", violations_path, :class => "button" %>
    </div>
    <div class="small-1 columns"></div>
  </div>
  <div class="row">
    <div class="alert-box please_log_in centered alert">Please log in</div>
    <div class="alert-box add_violation centered">Successfully added to watchlist!</div>
    <div class="alert-box remove_violation centered">Successfully removed from watchlist!</div>
  </div>
  <br>
  <% if @violation.restaurants.length == 0 %>
    <h3 class= "centered">There are no restaurants with this violation.</h3>
  <% else %>
    <h2>Restaurants with this violation</h2>
    <% hash = @violation.restaurants.group_by {|r| r.zip} %>
    <% hash.sort.each do |k, v|%>
      <h4><%= link_to k, zip_path(k), 'data-no-turbolink' => true %></h4>
      <%v.each do |r|%>
        <%= link_to r.name, restaurant_path(r), 'data-no-turbolink' => true %><br/>
      <% end %><br/>
    <% end %>
  <% end %>
  <br/>
</div>