config/routes.rb
RestaurantRails::Application.routes.draw do
get '/cuisines/:id' => 'cuisines#show', as: 'cuisine'
get '/cuisines' => 'cuisines#index', as: 'cuisines'

get '/pages/' => 'pages#index', as: 'home'
post '/pages/' => 'pages#search', as: 'search'

get '/restaurants' => 'restaurants#index', as: 'restaurants'
post 'restaurants' => 'restaurants#index'
get "/restaurants/add_restaurant/:id" => 'restaurants#add_restaurant', as: 'add_restaurant'
get "/restaurants/remove_restaurant/:id" => 'restaurants#remove_restaurant', as: 'remove_restaurant'
get '/restaurants/:id' => 'restaurants#show', as: 'restaurant'

get '/users/:id/remove_restaurant_from_profile' => 'users#remove_restaurant_from_profile', as: 'remove_restaurant_from_profile'
get '/users/:id/remove_violation_from_profile' => 'users#remove_violation_from_profile', as: 'remove_violation_from_profile'

get '/violations/:id' => 'violations#show', as: 'violation'
get '/violations' => 'violations#index', as: 'violations'
get "/violations/add_violation/:id" => 'violations#add_violation', as: 'add_violation'
get '/violations/remove_violation/:id' => 'violations#remove_violation', as: 'remove_violation'

get '/zipcodes/:id' => 'zipcodes#show', as: 'zip'
get '/zipcodes' => 'zipcodes#index'
get "/zipcodes/add_zipcode/:id" => 'zipcodes#add_zipcode', as: 'add_zipcode_show'
get '/zipcodes/remove_zipcode/:id' => 'zipcodes#remove_zipcode', as: 'remove_zipcode_show'


delete '/sessions' => 'sessions#destroy'
get '/sessions/new' => 'sessions#new', as: 'new_session'
post '/sessions' => 'sessions#create'
get 'auth/:provider/callback' => 'sessions#create'
get 'auth/failure' => redirect('/')
get 'signout' => 'sessions#destroy', as: 'signout'

get "/users" => 'users#new'
get "/users/new" => 'users#new', as: "new_user"
post "/users" => 'users#create'

get "/users/:id/edit" => 'users#edit', as: "edit_user"
patch "/users/:id" => 'users#update'

get "/users/:id" => 'users#show', as: "user"
get "/users/remove_zip/:id" => 'users#remove_zip', as: "remove_zip"
delete "/users/:id" => 'users#destroy', as: "destroy_user"

root 'pages#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :restaurant_violations
  has_many :violations, through: :restaurant_violations
  
  has_many :restaurant_cuisines
  has_many :cuisines, through: :restaurant_cuisines

  has_many :user_restaurants
  has_many :users, through: :user_restaurants

  belongs_to :zipcode

  extend FriendlyId
  friendly_id :name, use: :slugged

  before_save :slugify

  def zipify
    self.zipcode_id = self.ziparg
    self.save
  end
  
  def ziparg
    Zipcode.find_by(zip: self.zip).id
  end

  def slugify
    self.slug = self.slug_arg
  end
  
  def slug_arg
    # puts "name: #{name}"
    self.name.downcase.gsub(" ", "-").gsub("/", "-") + "-" + self.phone.to_i.to_s
  end

  def phone_num
    self.phone.to_s.strip.split('').insert(3, "-").insert(7, "-").join()[0,12]
  end

  def self.zip_list(zip_code)
    Restaurant.where(zip: zip_code)
  end

  def self.all_zips
    self.all.collect do |r|
      r.zip
    end.uniq
  end

  def address
    @address = "#{self.building_number} #{self.street_name}, #{self.zip}"
    @address
  end

  def self.worst_restaurant_in_zip(zip_code, num=1)
    r = Restaurant.zip_list(zip_code).sort do |a,b|
      if a.score == nil
        1
      elsif b.score == nil
        -1
      else
        b.score <=> a.score
      end
    end

    if num == 1
      r.first
    else
      r[0,num]
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  before_action :set_user, only: [:add_restaurant, :remove_restaurant]
  before_action :login_required, :only => [:add_restaurant]

  def show
  end

  def add_restaurant
    r = Restaurant.find(params[:id])
    @user.restaurants << r
  end

  def remove_restaurant
    @user.user_restaurants.where(restaurant_id: params[:id]).destroy_all
  end

  def index
    if params[:q] && params[:q][:name_cont].length < 3
      flash[:notice] = "Your search must be at least 3 characters long!"
      params.delete(:q)
    end
    @search = Restaurant.search(params[:q])
    @found_restaurants = @search.result
  end
  
  private

  def set_user
    @user = current_user
  end

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:id]) 
  end
end

app/views/restaurants/_restaurant.html.erb
<%= content_tag :h3, link_to(restaurant.name, restaurant_path(restaurant), 'data-no-turbolink' => true), id: restaurant.name %>
<%= content_tag :h4, restaurant.phone_num %>
<%= content_tag :h4, restaurant.address %>
<% restaurant.cuisines.each do |c| %>
  <%= content_tag :h3, link_to(c.description, cuisine_path(c.id)) %>
<% end %>
<h3><%= 
  if restaurant.grade == "A"
    image_tag 'a.jpg', class: "grade"
  elsif restaurant.grade == "B"
    image_tag 'b.jpg', class: "grade"
  elsif restaurant.grade == "C"
    image_tag 'c.jpg', class: "grade"
  else
    image_tag 'pending.jpg', class: "grade"
  end %>
  Violation points: <%= restaurant.score %>
</h3>
<ol>
  <% restaurant.violations.each do |vio| %>
    <%= content_tag :li, link_to(vio.description, violation_path(vio.id)) %>
  <% end %>
</ol>
<br>

app/views/restaurants/add_restaurant.js.erb
$(".add_rest_watchlist").hide();
$(".remove_rest_watchlist").css( "display", "block").show();

$(".add_restaurant").fadeIn(900, function(){
  $(".add_restaurant").fadeOut(300)
});

app/views/restaurants/index.html.erb
<div class="small-12 columns row search_form">
  <h3 class="centered">Search by Restaurant</h3>
  <%= search_form_for @search do |f| %>
    <div class="small-8 columns">
    <%= f.text_field :name_cont, :placeholder => "Name Contains..." %>
    </div>
    <div class="small-4 columns">
    <%= f.submit 'Search', :class => "button" %>  
    </div>
  <% end %>
</div>


<div class="small-7 columns">  
  <% if params[:q] %>
    <div class="search">
      <% if @found_restaurants == [] %>
        <div data-alert class="alert-box success radius" style="display:block">Search returned 0 results</div>
      <% else %>
      <h2>Search Results</h2>
        <ol>
        <% @found_restaurants.each do |r| %>
          <li><%= link_to r.name, restaurant_path(r) %>
            <ul><li><%= r.address%></li></ul>
          </li>
        <% end %>
        </ol>
      <% end %>
    </div>
  <% end %>
</div>

app/views/restaurants/remove_restaurant.js.erb
$(".remove_rest_watchlist").hide();
$(".add_rest_watchlist").css( "display", "block").show();

$(".remove_restaurant").fadeIn(900, function(){
  $(".remove_restaurant").fadeOut(300)
});

app/views/restaurants/show.html.erb
<head>
  <title>
    <%= "#{@restaurant.name} -- HELP! Bad Restaurants in New York City" %>
  </title>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyALUMEVvLlZ-4U2LSSVm3LhwtjbIO223qY&sensor=false">
  </script>    
  <% bad_r = @restaurant %>
  <% coords1 = Geocoder.coordinates(bad_r.address) %>

  <script type="text/javascript">

      function initialize() {

        var ll_worst1 = new google.maps.LatLng(<%=coords1[0]%>, <%=coords1[1]%>);

        var worst_string1 = "<%= "<h3>#{bad_r.name}</h3>#1 worst in #{bad_r.zip}<br><br>Extra 'flavor' with every meal!<p>" %>";

        var worst_info1 = new google.maps.InfoWindow({
          content: worst_string1
        });

        var mapOptions = {
          center: new google.maps.LatLng(<%=coords1[0]%>, <%=coords1[1]%>),
          zoom: 15
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);

        var marker_worst1 = new google.maps.Marker({
          position: ll_worst1,
          map: map,
          animation: google.maps.Animation.DROP,
          title: "#1 Worst Restaurant"
        }); 
 

        google.maps.event.addListener(marker_worst1, 'click', function() {
          worst_info1.open(map,marker_worst1);
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
  </script>
</head>
<body>
  <div id="content-below-bar">
    <div class="medium-6 columns">
      <div class="_list rest_list">
        <h2><%= 
          if @restaurant.grade == "A"
            image_tag("a.jpg", class: "grade")
          elsif @restaurant.grade == "B"
            image_tag("b.jpg", class: "grade")
          elsif @restaurant.grade == "C"
            image_tag("c.jpg", class: "grade")
          else
            image_tag("pending.jpg", class: "grade")
          end %>
          Violation points: <%= @restaurant.score %>
        </h2>
        <p>Last grade date: <%= @restaurant.date.to_formatted_s(:long) %></p>
        <ol>
          <% @restaurant.violations.each do |vio| %>
            <%= content_tag :li, link_to(vio.description, violation_path(vio.id)) %>
          <% end %>
        </ol>
      </div>
      <div class="row">
        <% if current_user == nil || !current_user.restaurants.include?(@restaurant) %>
          <%= content_tag "div", class: "medium-6 columns" do %>
            <%= link_to "Add to Watchlist", add_restaurant_path(@restaurant.id), remote: true, class: "button add_rest_watchlist", data: {user: signed_in?}, style: "display: block" %>
          <% end %>
          <div class="medium-6 columns">
              <%= link_to "Remove from Watchlist", remove_restaurant_path(@restaurant.id), remote: true, class: "button remove_rest_watchlist no_display alert" %>
          </div>
        <% else %>
          <div class="medium-6 columns">
            <%= link_to "Add to Watchlist", add_restaurant_path(@restaurant.id), remote: true, class: "button add_rest_watchlist no_display"%>
          </div>
          <div class="medium-6 columns">
              <%= link_to "Remove from Watchlist", remove_restaurant_path(@restaurant.id), remote: true, class: "button remove_rest_watchlist alert", style: "display: block" %>
          </div>
        <% end %>
        <div class="medium-6 columns">
          <a href="/restaurants" class="button">Restaurants Index</a>
        </div>
      </div>
      <div class="row">
        <div class="alert-box please_log_in centered alert">Please log in</div>
        <div class="alert-box add_restaurant centered"> Successfully added to watchlist!</div>
        <div class="alert-box remove_restaurant centered"> Successfully removed from watchlist!</div>
      </div>
    </div>
    <div class="medium-5 small-block-grid-5 columns">
      <div class="row">
        <div id="map-canvas">
        </div><br>
     </div>
      <div>
        <div class="medium-9 small-block-grid-9 restaurant-info">
          <h2><%= @restaurant.name %></h2>
          <h3><%= @restaurant.phone_num %></h3>
          <h3><%= "#{@restaurant.building_number} #{@restaurant.street_name}" %>, 
          <a href="/zipcodes/<%= @restaurant.zip %>" data-no-turbolink="true"><%= @restaurant.zip %></a></h3>
          <% @restaurant.cuisines.each do |c| %>
          <h3><%= link_to c.description, cuisine_path(c) %></h3>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>