config/routes.rb
RestaurantRails::Application.routes.draw do
get '/cuisines/:id' => 'cuisines#show', as: 'cuisine'
get '/cuisines' => 'cuisines#index', as: 'cuisines'

get '/pages/' => 'pages#index', as: 'home'
post '/pages/' => 'pages#search', as: 'search'

get '/restaurants' => 'restaurants#index', as: 'restaurants'
post 'restaurants' => 'restaurants#index'
get "/restaurants/add_restaurant/:id" => 'restaurants#add_restaurant', as: 'add_restaurant'
get "/restaurants/remove_restaurant/:id" => 'restaurants#remove_restaurant', as: 'remove_restaurant'
get '/restaurants/:id' => 'restaurants#show', as: 'restaurant'

get '/users/:id/remove_restaurant_from_profile' => 'users#remove_restaurant_from_profile', as: 'remove_restaurant_from_profile'
get '/users/:id/remove_violation_from_profile' => 'users#remove_violation_from_profile', as: 'remove_violation_from_profile'

get '/violations/:id' => 'violations#show', as: 'violation'
get '/violations' => 'violations#index', as: 'violations'
get "/violations/add_violation/:id" => 'violations#add_violation', as: 'add_violation'
get '/violations/remove_violation/:id' => 'violations#remove_violation', as: 'remove_violation'

get '/zipcodes/:id' => 'zipcodes#show', as: 'zip'
get '/zipcodes' => 'zipcodes#index'
get "/zipcodes/add_zipcode/:id" => 'zipcodes#add_zipcode', as: 'add_zipcode_show'
get '/zipcodes/remove_zipcode/:id' => 'zipcodes#remove_zipcode', as: 'remove_zipcode_show'


delete '/sessions' => 'sessions#destroy'
get '/sessions/new' => 'sessions#new', as: 'new_session'
post '/sessions' => 'sessions#create'
get 'auth/:provider/callback' => 'sessions#create'
get 'auth/failure' => redirect('/')
get 'signout' => 'sessions#destroy', as: 'signout'

get "/users" => 'users#new'
get "/users/new" => 'users#new', as: "new_user"
post "/users" => 'users#create'

get "/users/:id/edit" => 'users#edit', as: "edit_user"
patch "/users/:id" => 'users#update'

get "/users/:id" => 'users#show', as: "user"
get "/users/remove_zip/:id" => 'users#remove_zip', as: "remove_zip"
delete "/users/:id" => 'users#destroy', as: "destroy_user"

root 'pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= analytics_init if Rails.env.production? %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Avoid -- Which NYC Restaurant is Eating You?</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

    <%= render '/zipcodes/map' if content_for?(:zip_nav) %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Avoid", root_url %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li<%= yield(:rest_nav) if content_for?(:rest_nav) %>><%= link_to "Restaurant Search", restaurants_path %>
        </li>
          <li<%= yield(:zip_nav) if content_for?(:zip_nav) %>><%= link_to "Zipcode Search", zipcodes_path %></li>
          <li<%= yield(:vio_nav) if content_for?(:vio_nav) %>><%= link_to "Violation Search", violations_path %>
          </li>
          <li<%= yield(:cuis_nav) if content_for?(:cuis_nav) %>><%= link_to "Cuisine List", cuisines_path %></li>
          <% if !signed_in? %>
            <li><%= link_to image_tag('active_200.png'), "/auth/facebook" %></li>
            <li><%= link_to "Sign In", "/sessions/new" %></li>
          <% else %>
            <li><a href="<%= user_path(current_user) %>">
              <%if current_user.image_url != nil  %>
                <img src=<%= current_user.image_url %>>
              <% else %>
                Hi, <%= current_user.name %>!
              <% end %>
            </a></li>
          <% end %>
        </ul>

        <!-- Left Nav Section -->
      </section>
    </nav>
    <p><%= yield %></p>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/cuisines.html.erb
<% content_for :cuis_nav do %>
  <%= "class = active" %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/restaurants.html.erb
<% content_for :rest_nav do %>
  <%= "class = active" %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/violations.html.erb
<% content_for :vio_nav do %>
  <%= "class = active" %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/zipcodes.html.erb
<% content_for :zip_nav do %>
  <%= "class = active" %>
<% end %>
<%= render template: 'layouts/application' %>